In [2]:
import numpy as np

In [3]:
arr1=np.array([[1,2,2,3],[5,6,7,8]])
arr1.view()

array([[1, 2, 2, 3],
       [5, 6, 7, 8]])

In [4]:
arr1*arr1 #multiplying arrays

array([[ 1,  4,  4,  9],
       [25, 36, 49, 64]])

In [5]:
arr1 ** 3 #vector scalar

array([[  1,   8,   8,  27],
       [125, 216, 343, 512]], dtype=int32)

In [6]:
1/arr1 #reciprocation

array([[ 1.        ,  0.5       ,  0.5       ,  0.33333333],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ]])

In [7]:
np.array([[range(i,i+3) for i in [2,4,6,8]]]) # 2d array creation from using for and range

array([[[ 2,  3,  4],
        [ 4,  5,  6],
        [ 6,  7,  8],
        [ 8,  9, 10]]])

In [8]:
np.arange(3,20,4) #similar to python range

array([ 3,  7, 11, 15, 19])

In [9]:
np.linspace(3,20,4) # distributes 4 values between 3 and 20 

array([  3.        ,   8.66666667,  14.33333333,  20.        ])

In [10]:
np.zeros((3,4), dtype='int32') # 3*4 array full of 0s

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones((3,4), dtype='int32') #3*4 array full of 1s

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [12]:
np.full((3,5),42) # 3*5 array full of any integer. Here, 42.

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

## Random values

In [26]:
np.random.random(3) # an array filled with random values btwn 0 and 1

array([ 0.84762881,  0.84531142,  0.18204507])

In [18]:
np.random.random((3,4)) # 3*4 array of uniformly distributed values between 0 and 1

array([[ 0.50304363,  0.42271348,  0.11101067,  0.62720502],
       [ 0.39359026,  0.43258902,  0.13642325,  0.77391581],
       [ 0.40607665,  0.11236074,  0.41111099,  0.12704902]])

In [14]:
np.random.normal(0,10,(3,3)) #3*3 array of normally distributed values with mean 0 and Standard Deviation 1 

array([[ -8.80788701,  -3.73573482,   9.90814897],
       [  4.21394817,  -4.98879461,  11.17141523],
       [ 11.76457397, -15.73724452,  13.36574807]])

In [15]:
np.random.randn((10)) # normally distributed values with mean 0 and Standard Deviation 1 

array([ 0.2367131 ,  0.08735975, -0.83791714, -0.38014128, -0.40572086,
       -0.0952993 , -1.00620614,  0.47898988, -1.41978208, -0.1983284 ])

In [21]:
np.random.randn(4,3) # 2D array of normally distributed values with mean 0 and Std of 1
# same as np.random.random((4,3)). Notice the Difference!!

array([[-1.90044423,  1.90503347, -0.80921672],
       [-0.11802096, -0.16792237,  0.1328306 ],
       [ 0.08930411, -0.5107406 , -0.4453968 ],
       [ 1.81690499, -0.23190645,  0.29684799]])

In [16]:
np.random.randint(0,20,(3,3)) # 3*3 array of random ints between 0 to 20
# similar to np.random.randint(20,size=(3,3))

array([[17,  7, 16],
       [17, 12, 11],
       [10, 15, 15]])

In [17]:
np.random.randint(0,20,10) # 1d array of  random values btwn 0 to 20
# similar to np.random.randint(20, size=10)

array([ 3,  9, 18, 19,  8,  8, 13,  0, 16, 11])

## other stuff

In [18]:
np.empty(4) 

array([  3.        ,   8.66666667,  14.33333333,  20.        ])

In [19]:
ar1=np.eye(4) # 4*4 identity matrix
ar1

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

*Fancy indexing*

In [20]:
ar_length=ar1.shape[1] #length of one row
ar_length

4

In [21]:
for i in range(ar_length):
    ar1[i]=i
ar1

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.]])

In [22]:
ar1[[2,0,3,1]] # Fancy indexing happens here

array([[ 2.,  2.,  2.,  2.],
       [ 0.,  0.,  0.,  0.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [23]:
ar1.swapaxes(1,0) # self-explanatory

array([[ 0.,  1.,  2.,  3.],
       [ 0.,  1.,  2.,  3.],
       [ 0.,  1.,  2.,  3.],
       [ 0.,  1.,  2.,  3.]])

In [24]:
np.random.seed(0)
x3 = np.random.randint(10, size=(3, 4, 5))
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:", x3.dtype)
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype: int32
itemsize: 4 bytes
nbytes: 240 bytes
