In [2]:
import numpy as np

In [3]:
x=np.random.randint(10, size=6) # One-dimensional array
x

array([5, 5, 4, 5, 5, 7])

## Array Slicing

In [4]:
x[4:7] # slicing

array([5, 7])

In [5]:
x[::-1] # reversed array

array([7, 5, 5, 4, 5, 5])

In [6]:
x[::2] #every other element

array([5, 4, 5])

In [7]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [8]:
x2

array([[3, 8, 5, 9],
       [2, 4, 3, 0],
       [5, 7, 2, 3]])

In [9]:
x2[:2:,:3:] # slicing a 2d array

array([[3, 8, 5],
       [2, 4, 3]])

In [10]:
x2[:,1:] # removing the first column
# similar to x2[:3,1:]

array([[8, 5, 9],
       [4, 3, 0],
       [7, 2, 3]])

In [11]:
x2[:, 0] #getting only the first column
# almost similar to x2[:3,:1]. Similar to x2[:3,0]

array([3, 2, 5])

In [12]:
x2[0,:] # getting only the first row
# almost similar to x2[:1,:4]. Similar to x2[0,:4] and x2[0]

array([3, 8, 5, 9])

In [13]:
x2[:,::-1] #reversomg column order

array([[9, 5, 8, 3],
       [0, 3, 4, 2],
       [3, 2, 7, 5]])

In [14]:
x2[::-1,:4] #reversing row order

array([[5, 7, 2, 3],
       [2, 4, 3, 0],
       [3, 8, 5, 9]])

In [15]:
x2[::-1,::-1] # reverse all

array([[3, 2, 7, 5],
       [0, 3, 4, 2],
       [9, 5, 8, 3]])

## Copying an Array

In [16]:
x2_copy=x2[:2,:2].copy() #copying an array
x2_copy

array([[3, 8],
       [2, 4]])

## Reshaping of Arrays

In [38]:
grid=np.random.randint(0,20,12)
grid

array([ 8, 10, 18,  1,  1, 10,  9,  6,  3, 14, 12,  4])

In [39]:
g=grid.reshape((3,4)) # from 1D to 2D
g

array([[ 8, 10, 18,  1],
       [ 1, 10,  9,  6],
       [ 3, 14, 12,  4]])

In [41]:
grid.reshape(1,12)

array([[ 8, 10, 18,  1,  1, 10,  9,  6,  3, 14, 12,  4]])

In [42]:
grid[np.newaxis,:]

array([[ 8, 10, 18,  1,  1, 10,  9,  6,  3, 14, 12,  4]])

In [50]:
g3=grid.reshape([3,2,2]) # 3D array
g3

array([[[ 8, 10],
        [18,  1]],

       [[ 1, 10],
        [ 9,  6]],

       [[ 3, 14],
        [12,  4]]])

In [51]:
g.T # transposing the array

array([[ 8,  1,  3],
       [10, 10, 14],
       [18,  9, 12],
       [ 1,  6,  4]])

In [52]:
np.dot(g,g.T) #dot product of the tow

array([[489, 276, 384],
       [276, 218, 275],
       [384, 275, 365]])

In [53]:
g3.transpose((1,0,2))

array([[[ 8, 10],
        [ 1, 10],
        [ 3, 14]],

       [[18,  1],
        [ 9,  6],
        [12,  4]]])

## Concatenation

In [22]:
np.concatenate([g,g]) #this concatenation happens along the 1st axis (zero-indexed) or vertically

array([[13,  3,  3],
       [12,  4,  4],
       [12, 12,  1],
       [13,  3,  3],
       [12,  4,  4],
       [12, 12,  1]])

In [23]:
np.concatenate([g,g],axis=1) # this one happens horizontally

array([[13,  3,  3, 13,  3,  3],
       [12,  4,  4, 12,  4,  4],
       [12, 12,  1, 12, 12,  1]])

*Mixed-dimension array concatenation*

In [24]:
x=[1,2,42]

In [25]:
np.vstack([x,g]) # stacking them vertically

array([[ 1,  2, 42],
       [13,  3,  3],
       [12,  4,  4],
       [12, 12,  1]])

In [26]:
y=np.array([1,2,42]).reshape((3,1))
y

array([[ 1],
       [ 2],
       [42]])

In [27]:
np.hstack([y,g]) # stacking them horizontally 

array([[ 1, 13,  3,  3],
       [ 2, 12,  4,  4],
       [42, 12, 12,  1]])

## Splitting Arrays

In [28]:
z=np.array(range(7))
z

array([0, 1, 2, 3, 4, 5, 6])

In [29]:
np.split(z,[3,5]) # 1d array

[array([0, 1, 2]), array([3, 4]), array([5, 6])]

In [30]:
xy=np.arange(16).reshape(4,4)
xy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
xy1,xy2=np.vsplit(xy,[2]) # 2d array vertical split
xy3,xy4=np.hsplit(xy,[2]) # 2d array horizontal split

In [32]:
print(xy1,'\n')
print(xy2)

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]]


In [33]:
print(xy3,'\n')
print(xy4)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
