## Array input output

In [1]:
import numpy as np

In [13]:
arr =np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [9]:
np.save('myarr',arr)

In [17]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1 = np.load('myarr.npy')
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.savez('ziparray.npz',x=arr1,y=arr2)

In [21]:
archive_array = np.load('ziparray.npz')

In [22]:
archive_array['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
ar=np.array([[1,2,3],[4,5,6]])

In [25]:
np.savetxt('mytextarr.txt',ar,delimiter=',')

In [35]:
arrtxt=np.loadtxt('mytextarr.txt',delimiter=',')
arrtxt

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])