# UNIVERSAL FUNCTIONS  aka * _ufuncs_ *

In [1]:
import numpy as np

In [2]:
arr=np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [4]:
np.exp(arr) # e to the power of o ,1 ,2 ...

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [5]:
A=np.random.randn(10)

In [6]:
A

array([ 0.170608  ,  0.67775897,  0.74724882, -0.07523653,  1.22024437,
       -1.46003022,  0.69342812, -0.11490999, -0.55726125, -1.22812172])

In [8]:
B=np.random.randn(10)
B

array([-1.6992368 ,  0.12884683, -1.21492533, -0.74702692, -1.65843467,
       -1.30252045,  0.33179111,  0.44558955, -0.60285403,  0.0822155 ])

In [9]:
# Binary functions
np.add(A,B)

array([-1.52862879,  0.8066058 , -0.46767651, -0.82226345, -0.4381903 ,
       -2.76255067,  1.02521923,  0.33067956, -1.16011528, -1.14590622])

In [10]:
np.maximum(A,B)

array([ 0.170608  ,  0.67775897,  0.74724882, -0.07523653,  1.22024437,
       -1.30252045,  0.69342812,  0.44558955, -0.55726125,  0.0822155 ])

In [11]:
np.minimum(A,B)

array([-1.6992368 ,  0.12884683, -1.21492533, -0.74702692, -1.65843467,
       -1.46003022,  0.33179111, -0.11490999, -0.60285403, -1.22812172])

##### [Numpy Documentation](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html)
```python
import webbrowser as wb
wb.open('https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html')
```

In [14]:
big_array = np.random.randint(1, 100, size=1000000)

In [17]:
np.random.seed(0)
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

### It takes several seconds to compute these million operations and to store the result!

In [18]:
%timeit compute_reciprocals(big_array)

4.33 s ± 49 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### The bottleneck here is not the operations themselves, but...
# the TYPE-CHECKING and FUNCTION DISPACHES ...
#### ... that CPython must do at each cycle of the loop.
*Python first examines the object’s type and does a dynamic lookup of the correct function to use for that type. *

*If we were working in compiled code instead, this type specification would be known before the code executes and the result could be computed much more efficiently.*